workflows:
  maui-ios:
    name: Dotnet MAUI iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: io.codemagic.maui.weather
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET_BIN:  $CM_BUILD_DIR/dotnet/dotnet
    scripts:
      - name: Install dotnet sdk
        script: |
          chmod +x dotnet-install.sh
          ./dotnet-install.sh
      - name: Install MAUI
        script: |
          $DOTNET_BIN nuget locals all --clear 
          $DOTNET_BIN workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          $DOTNET_BIN workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json      
      - name: Build
        script: |
          cd src
          $DOTNET_BIN publish -f net6.0-ios -c Release -p:BuildIpa=True -o ../artifacts
    artifacts:
        - ./artifacts/*.ipa
       
  maui-android:
    name: Dotnet MAUI Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - marijanappkey
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET_BIN: $CM_BUILD_DIR/dotnet/dotnet
        PACKAGE_NAME: "io.codemagic.maui.weather"
    scripts:
      - name: Install dotnet sdk
        script: |
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH
      - name: Install MAUI
        script: |
          $DOTNET_BIN nuget locals all --clear 
          $DOTNET_BIN workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          $DOTNET_BIN workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json      
      - name: Build
        script: |
          cd src
          $DOTNET_BIN publish -f net6.0-android -c Release -p:BuildIpa=True -o ../artifacts
          # dotnet publish -f:net7.0-android -c:Release /p:AndroidSigningKeyPass=mypassword /p:AndroidSigningStorePass=mypassword
    artifacts:
        - ./artifacts/*.aab
